[tool.poetry]
name = "portfolio"
version = "0.1.0"
description = ""
authors = ["Vika <kaledaviktoriya@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
